name: "Delivery and deploy"

on:
  push:
    branches:
      - main
      - dev
      - pipeline

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.getversion.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version
        id: getversion
        run: |
          echo "version=$(jq -r '.version' < package.json)" >> $GITHUB_OUTPUT

  build:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Update package.json version
        run: |
          version=${{ needs.release.outputs.VERSION }}
          contents=$(jq --arg version "$version" '.version = $version' package.json) && \
          echo "$contents" > package.json

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USER }}/user-management:${{ needs.release.outputs.VERSION }}
            ${{ secrets.DOCKERHUB_USER }}/user-management:${{ github.ref == 'refs/heads/main' && 'latest' || 'nightly' }}
